window.ZETA_SAMPLES = [
  {
    "id": "amdo_v1_t1",
    "dialect": "amdo",
    "genre": "read",
    "speaker": "amdo_f1_read",
    "text": "ཧ་ལ་མཚེའུ་འགྲམ་གྱི་གངས་རི་འོད་ལམ་ལམ་དུ་འཚེར།",
    "source": "https://epaper.tibet3.com/qhzwb/html/202604/03/content_264870.html",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v1_t1.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v1_t1.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v1_t1.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v1_t1.wav"
  },
  {
    "id": "amdo_v1_t2",
    "dialect": "amdo",
    "genre": "read",
    "speaker": "amdo_f1_read",
    "text": "ལྷ་རིས་པའི་པིར་སྨྱུག་ལས་ཐོན་པའི་ཐང་ག་ཇི་བཞིན་རིམ་གྱིས་མིག་ལ་མངོན་ཡོང་།",
    "source": "https://epaper.tibet3.com/qhzwb/html/202504/04/content_212447.html",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v1_t2.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v1_t2.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v1_t2.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v1_t2.wav"
  },
  {
    "id": "amdo_v1_t3",
    "dialect": "amdo",
    "genre": "read",
    "speaker": "amdo_f1_read",
    "text": "འདིར་བསྡད་ན་སྐྱིད་པོ་ཡིན་ལ་སྟབས་བདེ་ཡང་རེད།",
    "source": "https://epaper.tibet3.com/qhzwb/html/202504/04/content_212447.html",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v1_t3.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v1_t3.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v1_t3.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v1_t3.wav"
  },
  {
    "id": "amdo_v1_t4",
    "dialect": "amdo",
    "genre": "read",
    "speaker": "amdo_f1_read",
    "text": "སྔོན་ཆད་རིན་མེད་སྒོས་ཟ་ཁང་ནས་ཟ་མ་བཟའ་ཆོག་པ་ཐོས་མ་མྱོང་།",
    "source": "https://epaper.tibet3.com/m/qhzwb/20250214/207178",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v1_t4.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v1_t4.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v1_t4.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v1_t4.wav"
  },
  {
    "id": "amdo_v2_t1",
    "dialect": "amdo",
    "genre": "news",
    "speaker": "amdo_m3_news",
    "text": "ཞིང་ཆེན་དམངས་ཆེན་སྐབས་བཅུ་བཞི་པའི་རྒྱུན་ལས་ཨུ་ཡོན་ལྷན་ཁང་གི་གྲོས་ཚོགས་ཐེངས་ཉེར་གཅིག་པ་ཟི་ལིང་དུ་འཚོགས་པ།",
    "source": "https://epaper.tibet3.com/qhzwb/html/202604/03/content_264842.html",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v2_t1.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v2_t1.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v2_t1.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v2_t1.wav"
  },
  {
    "id": "amdo_v2_t2",
    "dialect": "amdo",
    "genre": "news",
    "speaker": "amdo_m3_news",
    "text": "མཚོ་སྔོན་གྱིས་རི་སྐྱེས་སྲོག་ཆགས་དང་རྩི་ཤིང་ལ་གཏོར་བརླག་བཏང་བའི་ཁྲིམས་འགལ་ཉེས་བསགས་ལ་རྩད་ཞིབ་ནན་མོ་བྱས་པ།",
    "source": "https://epaper.tibet3.com/qhzwb/html/202604/03/content_264847.html",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v2_t2.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v2_t2.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v2_t2.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v2_t2.wav"
  },
  {
    "id": "amdo_v2_t3",
    "dialect": "amdo",
    "genre": "news",
    "speaker": "amdo_m3_news",
    "text": "མགོ་ལོག་གིས་འཛད་སྤྱོད་སྐུལ་འདེད་བྱ་འགུལ་ལ་བརྟེན་ནས་མང་ཚོགས་ཀྱི་འཛད་སྤྱོད་ངར་ཤུགས་བསླངས་པ།",
    "source": "https://epaper.tibet3.com/qhzwb/html/202604/03/content_264851.html",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v2_t3.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v2_t3.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v2_t3.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v2_t3.wav"
  },
  {
    "id": "amdo_v2_t4",
    "dialect": "amdo",
    "genre": "news",
    "speaker": "amdo_m3_news",
    "text": "ནོར་ལུག་གི་གསོ་ཐབས་འཚོལ་ཞིབ་བྱས་ཏེ།ཕྱུག་འགྱུར་གྱི་ལམ་བུར་ལེགས་པར་བགྲོད་པ།",
    "source": "https://epaper.tibet3.com/qhzwb/html/202604/03/content_264869.html",
    "cosyvoice2": "assets/audio/cosyvoice2/amdo_v2_t4.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/amdo_v2_t4.wav",
    "dots_tts": "assets/audio/dots_tts/amdo_v2_t4.wav",
    "f5_tts": "assets/audio/f5_tts/amdo_v2_t4.wav"
  },
  {
    "id": "utsang_v1_t1",
    "dialect": "utsang",
    "genre": "read",
    "speaker": "utsang_f1_read",
    "text": "ང་རང་དོན་དག་ག་གེ་མོ་ཞིག་གི་ཆེད་དུ་མེ་འཁོར་ལ་བསྡད་དེ་གཞིས་ཀ་རྩེ་ནས་ལྷ་སར་འགྲོ་བའི་ལམ་དུ་ཞུགས།",
    "source": "https://e.xzxw.com/xzrbzw/202509/14/content_325697.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v1_t1.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v1_t1.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v1_t1.wav"
  },
  {
    "id": "utsang_v1_t2",
    "dialect": "utsang",
    "genre": "read",
    "speaker": "utsang_f1_read",
    "text": "ལམ་བར་དུ་བཀླག་བྱའི་དཔེ་དེབ་རེ་ཁྱེར་བ་ནི་ངའི་འཚོ་བའི་གོམས་གཤིས་ཤིག་ཏུ་གྱུར།",
    "source": "https://e.xzxw.com/xzrbzw/202509/14/content_325697.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v1_t2.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v1_t2.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v1_t2.wav"
  },
  {
    "id": "utsang_v1_t3",
    "dialect": "utsang",
    "genre": "read",
    "speaker": "utsang_f1_read",
    "text": "དེས་ལམ་གྱི་ངལ་དུབ་སེལ་ཐུབ་ལ་དུས་ཚོད་ཀྱང་ངོ་མ་འགྲོ་མགྱོགས་པོ་ཡོད་སྣང་ཤར།",
    "source": "https://e.xzxw.com/xzrbzw/202509/14/content_325697.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v1_t3.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v1_t3.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v1_t3.wav"
  },
  {
    "id": "utsang_v1_t4",
    "dialect": "utsang",
    "genre": "read",
    "speaker": "utsang_f1_read",
    "text": "དེས་རང་ཉིད་ལའང་སྐུལ་ལྕག་ཆེན་པོ་ཐེབས་འོང་།",
    "source": "https://e.xzxw.com/xzrbzw/202509/14/content_325697.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v1_t4.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v1_t4.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v1_t4.wav"
  },
  {
    "id": "utsang_v2_t1",
    "dialect": "utsang",
    "genre": "news",
    "speaker": "utsang_m3_news",
    "text": "ལྷོ་ཁ་གྲོང་ཁྱེར་གྱི་བདེ་འཇགས་ཐོན་སྐྱེད་དུས་བབ་རྒྱུན་མཐུད་ལེགས་སུ་ཕྱིན་པ།",
    "source": "https://e.xzxw.com/xzrbzw/202505/03/content_306652.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v2_t1.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v2_t1.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v2_t1.wav"
  },
  {
    "id": "utsang_v2_t2",
    "dialect": "utsang",
    "genre": "news",
    "speaker": "utsang_m3_news",
    "text": "གཡག་གི་བསམ་འདུན་གྱི་དཔེ་དེབ་ཡོངས་བསྒྲགས་ཚོགས་འདུ་འཚོགས་པ།",
    "source": "https://e.xzxw.com/xzrbzw/202505/03/content_306656.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v2_t2.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v2_t2.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v2_t2.wav"
  },
  {
    "id": "utsang_v2_t3",
    "dialect": "utsang",
    "genre": "news",
    "speaker": "utsang_m3_news",
    "text": "ལྷོ་ཁ་གྲོང་ཁྱེར་གྱིས་བྱ་ཐབས་སྣ་མང་སྤྱད་དེ་འདམ་ར་སྲུང་སྐྱོང་ལས་དོན་ལ་སྐུལ་འདེད་བཏང་བ།",
    "source": "https://e.xzxw.com/xzrbzw/202507/13/content_316904.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v2_t3.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v2_t3.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v2_t3.wav"
  },
  {
    "id": "utsang_v2_t4",
    "dialect": "utsang",
    "genre": "news",
    "speaker": "utsang_m3_news",
    "text": "བོད་ཀྱི་དྲ་རྒྱའི་བརྙན་པར་དུས་ཆེན་སྐབས་ལྔ་པའི་བྱ་དགའ་སྤྲོད་པའི་མཛད་སྒོ་ལྷ་སར་འཚོགས་པ།",
    "source": "https://e.xzxw.com/xzrbzw/202507/29/content_319220.html",
    "cosyvoice2": "assets/audio/cosyvoice2/utsang_v2_t4.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/utsang_v2_t4.wav",
    "dots_tts": "assets/audio/dots_tts/utsang_v2_t4.wav"
  },
  {
    "id": "kham_v1_t1",
    "dialect": "kham",
    "genre": "read",
    "speaker": "kham_f4_read",
    "text": "སྦྲང་ཆར་ཟིམ་ཟིམ་དུ་བབས་པའི་ཞོགས་པ་ཞིག་ལ་ང་རང་གྲོང་ཁྱེར་གྱི་ལྟེ་བའི་ཁུལ་གྱི་ཐོག་ཁང་མང་པོའི་ལྟག་རྒྱབ་ཀྱི་ཤིང་སྐས་རིང་མོར་འཛེགས་ཏེ་ཆོས་ཀྱི་འདུན་ས་འབར་ཁམས་དགོན་དུ་ཕྱིན།",
    "source": "https://tb.kangbatv.com/fj/sm/2018-05-04/274020.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v1_t1.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v1_t1.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v1_t1.wav"
  },
  {
    "id": "kham_v1_t2",
    "dialect": "kham",
    "genre": "read",
    "speaker": "kham_f4_read",
    "text": "ཤར་ཕྱོགས་ལྷུན་པོའི་རྩེ་ནས་རྟ་བདུན་དབང་པོ་དྲོད་ལམ་མེར་འཆར་བྱུང་ལ།",
    "source": "https://tb.kangbatv.com/fj/sm/2018-05-04/274020.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v1_t2.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v1_t2.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v1_t2.wav"
  },
  {
    "id": "kham_v1_t3",
    "dialect": "kham",
    "genre": "read",
    "speaker": "kham_f4_read",
    "text": "ནམ་མཁའ་སྔོ་ཞིང་དྭངས།",
    "source": "https://tb.kangbatv.com/fj/sm/2018-05-04/274020.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v1_t3.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v1_t3.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v1_t3.wav"
  },
  {
    "id": "kham_v1_t4",
    "dialect": "kham",
    "genre": "read",
    "speaker": "kham_f4_read",
    "text": "དེ་མིན་ད་རུང་གསེར་འོད་ལམ་ལམ་གྱི་འབར་ཁམས་དགོན་པའི་རྒྱ་ཕིབས་སོགས་མིག་མདུན་དུ་མངོན་བྱུང་དུས་ཡིད་སེམས་ཡོངས་སྤྲོ་བས་ཁེངས་སོང་།",
    "source": "https://tb.kangbatv.com/fj/sm/2018-05-04/274020.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v1_t4.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v1_t4.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v1_t4.wav"
  },
  {
    "id": "kham_v2_t1",
    "dialect": "kham",
    "genre": "news",
    "speaker": "kham_m1_news",
    "text": "༢༠༢༦ལོའི་སི་ཁྲོན་དཀར་མཛེས་ཀྱི་རི་ཁུལ་རིག་གནས་ཡུལ་སྐོར་དུས་ཆེན་འགོ་བརྩམ་ལ་ཉེ།",
    "source": "https://tb.kangbatv.com/xw/kbwsxw/2026-07-24/799668.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v2_t1.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v2_t1.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v2_t1.wav"
  },
  {
    "id": "kham_v2_t2",
    "dialect": "kham",
    "genre": "news",
    "speaker": "kham_m1_news",
    "text": "བདེ་ཆེན་ཁུལ་ཉིས་སྟོང་ཉེར་དྲུག་ལོའི་ཀྲུང་དབྱང་ནོར་སྲིད་ཀྱིས་ཡོངས་ཕན་དངུལ་རྩ་འཕེལ་རྒྱས་ལ་རྒྱབ་སྐྱོར་བྱེད་པའི་དཔེ་སྟོན་ཁུལ་དུ་བདམས།",
    "source": "https://tb.kangbatv.com/xw/kbwsxw/2026-07-24/799665.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v2_t2.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v2_t2.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v2_t2.wav"
  },
  {
    "id": "kham_v2_t3",
    "dialect": "kham",
    "genre": "news",
    "speaker": "kham_m1_news",
    "text": "བགྲོད་ལམ་གསར་པའི་ཐོག་འབད་པ་ཆེན་པོས་མདུན་དུ་སྐྱོད་པ་དང་མཐོ་སྒང་གི་གྲུབ་འབྲས་གསར་པ་གཏོད།",
    "source": "https://tb.kangbatv.com/xw/kbwsxw/2026-07-02/795795.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v2_t3.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v2_t3.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v2_t3.wav"
  },
  {
    "id": "kham_v2_t4",
    "dialect": "kham",
    "genre": "news",
    "speaker": "kham_m1_news",
    "text": "སི་ཝེས་ཙེར་ཡིན་པའི་བོད་རིགས་རོལ་དབྱངས་པ་བདེ་ཆེན་གྱི་ཀྲུང་གོའི་འཁྲབ་སྟོན་སུའུ་ཀྲོའུ་རུ་ལེགས་འགྲུབ་བྱུང་།",
    "source": "https://tb.kangbatv.com/xw/kbwsxw/2026-07-24/799670.html",
    "cosyvoice2": "assets/audio/cosyvoice2/kham_v2_t4.wav",
    "cosyvoice3": "assets/audio/cosyvoice3/kham_v2_t4.wav",
    "dots_tts": "assets/audio/dots_tts/kham_v2_t4.wav"
  }
];
